"""Path constants + on-disk config loader for labnotes-sync.

Single source of truth for where state lives — every other module imports
from here so that tests can swap paths via env vars without poking globals.
"""

from __future__ import annotations

import os
import tomllib
from dataclasses import dataclass
from pathlib import Path


# Repo root: scripts/sync/<this file> → parents[2] is the Aurash repo root.
REPO_ROOT = Path(__file__).resolve().parents[2]

# What gets snapshotted. Keep these aligned with the plan.
DB_PATH = REPO_ROOT / "backend" / "labnotes.db"
SECRETS_PATHS = [
    Path("backend/.env.local"),
    Path("frontend/.env.local"),
]

# Per-user state. Both are 0600 and must NOT be committed or uploaded.
USER_CFG_DIR = Path(
    os.environ.get("LABNOTES_SYNC_CONFIG_DIR", str(Path.home() / ".config" / "labnotes-sync"))
)
CONFIG_FILE = USER_CFG_DIR / "config.toml"
AGE_PASSPHRASE_FILE = USER_CFG_DIR / "age.passphrase"

# Caches under $HOME.
LOCK_FILE = Path.home() / ".cache" / "labnotes-sync.lock"
LOG_FILE = Path.home() / ".cache" / "labnotes-sync.log"
ALERT_FILE = Path.home() / ".cache" / "labnotes-sync.alert"

# Layout inside the HF Dataset.
DATASET_DB_PATH = "data/labnotes.db"
DATASET_SECRETS_PATH = "secrets.age"
DATASET_MANIFEST_PATH = "manifest.json"
MANIFEST_SCHEMA_VERSION = 1


@dataclass(slots=True)
class SyncConfig:
    repo_id: str  # e.g. "winbeau/labnotes-state"
    machine_id: str  # human-readable label, lands in manifest.pushed_by

    @classmethod
    def load(cls) -> "SyncConfig":
        if not CONFIG_FILE.exists():
            raise FileNotFoundError(
                f"{CONFIG_FILE} not found — run `make sync-bootstrap` first."
            )
        data = tomllib.loads(CONFIG_FILE.read_text(encoding="utf-8"))
        try:
            return cls(
                repo_id=data["hf"]["repo_id"],
                machine_id=data["machine"]["id"],
            )
        except KeyError as e:
            raise ValueError(
                f"{CONFIG_FILE} is missing required key {e}; re-run sync-bootstrap."
            ) from e

    @classmethod
    def write(cls, repo_id: str, machine_id: str) -> "SyncConfig":
        USER_CFG_DIR.mkdir(parents=True, exist_ok=True)
        # tomllib is read-only; hand-render the small file to avoid pulling tomli-w.
        body = (
            "# labnotes-sync config — generated by bootstrap.py\n"
            "[hf]\n"
            f'repo_id = "{repo_id}"\n'
            "\n"
            "[machine]\n"
            f'id = "{machine_id}"\n'
        )
        CONFIG_FILE.write_text(body, encoding="utf-8")
        CONFIG_FILE.chmod(0o600)
        return cls(repo_id=repo_id, machine_id=machine_id)
